version: "3"
services:
  app:
    build:
      context: "./.aero"
      dockerfile: Dockerfile
      args:
        WWWGROUP: "${WWWGROUP}"
    image: aero/8.3
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${WEB_PORT:-80}:80"
    environment:
      WWWUSER: "${WWWUSER}"
    networks:
      - aero
    volumes:
      - "./:/var/www/html"
      - "./.aero/config/nginx.conf:/etc/nginx/sites-enabled/99-user.conf"
      - "./.aero/config/php-pool.conf:/etc/php/8.3/fpm/pool.d/99-user.conf"
      - "./.aero/config/php-fpm.ini:/etc/php/8.3/fpm/conf.d/99-user.ini"
      - "./.aero/config/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf"
    depends_on:
      - db
      - cache
      - search
  db:
    image: mysql:8
    command: --max_allowed_packet=64M
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db:/var/lib/mysql
    networks:
      - aero
    healthcheck:
      test: [CMD, mysqladmin, ping, "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s
  cache:
    image: redis:alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - cache:/data
    networks:
      - aero
    healthcheck:
      test: [CMD, redis-cli, ping]
      retries: 3
      timeout: 5s
  search:
    image: elasticsearch:7.17.10
    ports:
      - "${ES_PORT:-9200}:9200"
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms${ES_MEMORY:-512}m -Xmx${ES_MEMORY:-512}m"
    ulimits:
      memlock: { soft: -1, hard: -1 }
    volumes:
      - search:/usr/share/elasticsearch/data
    networks:
      - aero
    healthcheck:
      test: [CMD, wget, "--no-verbose", "--spider", "http://localhost:9200"]
      retries: 3
      timeout: 5s
  mailpit:
    image: "axllent/mailpit:latest"
    ports:
      - "${MAILPIT_PORT:-1025}:1025"
      - "${MAILPIT_DASHBOARD_PORT:-8025}:8025"
    networks:
      - aero
networks:
  aero:
    driver: bridge
volumes:
  db:
    driver: local
  cache:
    driver: local
  search:
    driver: local
