#!/usr/bin/env bash

trap "exit 0" SIGINT
trap "exit 0" SIGTERM

cd /home/user

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER user
fi

if [ ! -d .composer ]; then
    mkdir .composer
fi

chmod -R ugo+rw .composer

if [ $# -gt 0 ]; then
    exec gosu $WWWUSER "$@"
else
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
