#!/usr/bin/env bash

trap "exit 0" SIGINT
trap "exit 0" SIGTERM

echo "uid: $WWWUSER"

if [ ! -z "$WWWUSER" ]; then
    echo "changing uid for user"
    usermod -u $WWWUSER user
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ $# -gt 0 ]; then
    exec gosu $WWWUSER "$@"
else
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
