#!/usr/bin/env bash

trap "exit 0" SIGINT
trap "exit 0" SIGTERM

cd /home/user

if [ ! -d .composer ]; then
    mkdir .composer
fi

chmod -R ugo+rw .composer

exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf